name = "blp-vega"
main = "worker.js"
compatibility_date = "2026-09-01"
workers_dev = true
preview_urls = false

[[ratelimits]]
name = "PER_IP"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 30
  period = 60
